title: The Kovri I2P Router Project
description: Kovri, a secure, private, untraceable C++ router implementation of I2P
baseurl: ""
permalink: /:title/
exclude: [".gitignore", "README.md"]


# Plugins
gems: 
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["en", "es", "ru"]

exclude_from_localizations: ["img", "css", "fonts"]